### ISSUE TITLE
Task 8: 

### ISSUE THREAD

**Issue by muellermartin** [UCL-INGI/INGInious-demo-tasks#5]
To my understanding task 8 ("Export generated files") should be solveable with following input:

```
#!/bin/bash

echo foobar > student/generated.txt
archive --add student/generated.txt
```

Unfortunately, the submission fails with the message "It seems the file cannot not be found. Did you use the archive API correctly ?"

With the help of the remote SSH inspection, the `run` script shows that there is a [check for the file at `/.__output/generated.txt`](https://github.com/UCL-INGI/INGInious-demo-tasks/blob/172be206c9248189f0f0e5d27db360d7349e4d99/tutorial/08_archive/run#L11).

Shouldn't this check be for `/archive/generated.txt` or `student/generated.txt`? But maybe I just don't understand the task or INGInious correctly.

**Comment by anthonygego** [comment]
You're right. The file is now supposed to be in ``/archive`` and the task was not updated. I'll update that.
